### ISSUE TITLE
I think we need to remove StreamComparator

### ISSUE THREAD

**Issue by johnynek** [Cascading/cascading-thrift#2]
I'll make a pull request, but I wanted to note that StreamComparator and compare are not likely consistent (unless thrift offers some guarantee we don't know).

I see a few approaches:

1) if the bytes are equal, the deserialized is equal, so we can handle that case.  If the bytes are not equal, we could deserialze and compare.

2) We could keep a LinkedHashMap-based cache to keep a mapping of bytes -> deserialized objects.  Depending on the sorting pattern, it may be save us from having to repeatedly deserialize the data, which might result in most of the gains of being lazy.  BTW: if someone is using a thrift object as a key in a group/cogroup that's a kind that they values may not be very diverse, and as such maybe the cache will cover all the distinct values we see.

3) We could just remove StreamComparator and (I believe) cascading will deserialize and call compare.  This should work as expected but be slower.

**Comment by nathanmarz** [comment]
The common case is that the compared elements are not equal, so #1 probably won't help very much. Let's just keep it simple and get rid of it altogether.

**Comment by sritchie** [comment]
I removed the stream comparison and published as version `0.2.3`. This is now available in Conjars and Clojars.
